# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "POD"
license = "MIT"
licenselink = "https://github.com/polipones/pod_hugo_theme/blob/main/LICENSE"
description = "A fast, clean, responsive Hugo theme"
homepage = "https://github.com/polipones/pod_hugo_theme"
tags = [
  "responsive",
  "simple",
  "clean",
  "light",
  "dark",
  "minimalist",
  "highlight.js",
  "search"
]
features = [
  "responsive",
  "single-column",
  "cover-image",
  "table-of-contents",
  "opengraph",
  "highlight.js",
  "favicon",
  "share-icons",
  "cover",
  "multilingual",
  "social-icons",
  "minified-assets",
  "theme-toggle",
  "menu-location-indicator",
  "scroll-to-top",
  "search"
]
min_version = "0.74.0"

[author]
  name = "Jan Picka"
  homepage = "https://github.com/polipones/"

# If porting an existing theme
[original]
  name = "PaperMod"
  author = "adityatelange"
  homepage = "https://adityatelange.github.io/hugo-PaperMod/"
  repo = "https://github.com/adityatelange/hugo-PaperMod"
